{'groups': 'all', 'params_to_try': {'delta_schooling': [0.5], 'xi': [0, 371990.3, 929975.75, 1859951.5, 3719903, 5579854.5], 'icus': [2900], 'tests': [[60000, 0]], 'testing': ['homogeneous'], 'eta': [0.1]}}
{'groups': 'all', 'params_to_try': {'delta_schooling': [0.5], 'xi': [0, 371990.3, 929975.75, 1859951.5, 3719903, 5579854.5], 'icus': [2900], 'tests': [[60000, 0]], 'testing': ['homogeneous'], 'eta': [0.1]}}
{'groups': 'all', 'params_to_try': {'delta_schooling': [0.5], 'icus': [2900], 'eta': [0.1], 'tests': [[0, 0]], 'xi': [30875194.900000002], 'testing': ['homogeneous']}}
results/time_gradient/xi-30875194_icus-2900_testing-homogeneous_natests-0_nmtests-0_T-90_startday-0_groups-all_dschool-0.500000_eta-0.100000_freq-90-14.yaml
300
(0.5, 0.29, 0.0, (7, 14), 'fitted-scaled', 'econ-scaled', 'oct21-scaled', 0.1, 308751949.0, 0.05, 2, 'time_gradient')
Total Population is: 1227.820999439713
The value of T is: 104
Missing starting point -- Running the initial heuristic.
/home/groups/daniancu/covid-optimization/covid-optimization
Traceback (most recent call last):
  File "/home/groups/daniancu/covid-optimization/covid-optimization/heuristics/linearization.py", line 1398, in run_heuristic_linearization
    with open("benchmarks/results/%s/%s"%(h,n)) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'benchmarks/results/time_gradient/xi-30875194_icus-2900_testing-homogeneous_natests-0_nmtests-0_T-90_startday-0_groups-all_dschool-0.500000_eta-0.100000_freq-90-14.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_linearization_heuristic_targetting_value.py", line 870, in <module>
    main()
  File "run_linearization_heuristic_targetting_value.py", line 142, in main
    run_lin_heur_and_save_yaml(delta, xi, icus, mtests, atests, n_days, region, test_freq, lockdown_freq, econ, init, eta, groups, start_day, trust_region_radius, max_inner_iterations_mult, initial_uhat, optimize_bouncing, scaling, money_scaling, targetActivities, targetGroups, targetTests)
  File "run_linearization_heuristic_targetting_value.py", line 181, in run_lin_heur_and_save_yaml
    dynModel = run_linearization_heuristic(simulation_params, experiment_params, start_day, trust_region_radius, max_inner_iterations_mult, initial_uhat, optimize_bouncing, targetActivities, targetGroups, targetTests)
  File "run_linearization_heuristic_targetting_value.py", line 323, in run_linearization_heuristic
    linearization.run_heuristic_linearization(dynModel, trust_region_radius, max_inner_iterations_mult, initial_uhat, optimize_bouncing, targetActivities, targetGroups, targetTests)
  File "/home/groups/daniancu/covid-optimization/covid-optimization/heuristics/linearization.py", line 1418, in run_heuristic_linearization
    result = yaml.load(file, Loader=yaml.FullLoader)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/reader.py", line 169, in update
    self.check_printable(data)
  File "/home/users/xwarnes/.local/lib/python3.6/site-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "benchmarks/results/time_gradient/xi-30875194_icus-2900_testing-homogeneous_natests-0_nmtests-0_T-90_startday-0_groups-all_dschool-0.500000_eta-0.100000_freq-90-14.yaml", position 0
srun: error: sh02-01n13: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=15369801.0
